### ISSUE TITLE
How test actions that use callApi()?

### ISSUE THREAD

**Issue by BrunoQuaresma** [CodingZeal/react-boilerplate#120]
How test actions that use callApi()?

**Comment by randycoulman** [comment]
We don't normally test our action creators directly, including those that use `callApi`.  They don't tend to have logic in them, so they don't need to be tested.

If I had a complex action creator that used `callApi`, I'd inject a mock or spy version of `callApi` and check that it was called with the arguments I expected.  We use [testdouble.js](https://github.com/testdouble/testdouble.js) for this kind of thing, but you can also use [sinon](http://sinonjs.org/) if you prefer.

If you're not familiar with this style of testing, the documentation for testdouble.js has lots of good information in it.

**Comment by BrunoQuaresma** [comment]
Thanks @randycoulman!
